### ISSUE TITLE
Extension domain's def of "Product" entity is slightly different from "Product" defined in DPP context

### ISSUE THREAD

**Issue by absoludity** [jargon-sh/issues#42]
The aatp.DLP domain imports the untp/DigitalProductPassport domain and specifically, `BovineAnimal` inherits from `dpp.Product`.

This results in the [`Product` entity being included in the DLP context](https://jargon.sh/user/aatp/DigitalLivestockPassport/v/working/artefacts/jsonldContexts/DigitalLivestockPassport.jsonld?class=DigitalLivestockPassport) [1] which wouldn't be an issue except that it is minutely different. Specifically, the `DPP.Product` defines the property `conformityClaim` as:

```
        "conformityClaim": {
          "@id": "untp-dpp:conformityClaim",
          "@type": "@id"
        },
```

whereas the `DLP.Product` has:

```
        "conformityClaim": {
          "@id": "untp-core:conformityClaim",
          "@type": "@id"
        },
```
(full diff at [2]).

Since the contexts of both DPP and DLP are included, this counts as an (illegal) redefinition. I've tried removing the untp-core import from DLP (since it's not referenced at all - only DPP is used), but it's still the same (also tried resaving twice). Why are we seeing a difference here, given DLP is importing the dpp.Product - it should be the same?

[1] I was about to write that "I'm not sure why it's needed, since `BovineAnimal` is defined as well", but checking the DLP context linked aboe, I see that `BovineAnimal` isn't actually defined at all? Is that expected?

[2] https://www.diffchecker.com/V1m4n1dj/

**Comment by colugo** [comment]
I suspect that DPP hasn't been saved again after some other issues were closed. Looking now, DPP has untp-core:conformityClaim.

So they seem the same to me. The bigger question is should they be untp-core, or untp-dpp?

<img width="1105" alt="Image" src="https://github.com/user-attachments/assets/fb77a027-cd5b-4a00-8454-ea15d6295215" />

I also see BovineAnimal in DLP context?
<img width="1104" alt="Image" src="https://github.com/user-attachments/assets/82d27b6d-0131-4572-8686-456c1330ee65" />

**Comment by absoludity** [comment]
> I suspect that DPP hasn't been saved again after some other issues were closed. Looking now, DPP has untp-core:conformityClaim.

Hmm, I'm using the latest release, but yes, it could be that there have been jargon changes I requested since then. I'll update, thanks.

> 
> So they seem the same to me. The bigger question is should they be untp-core, or untp-dpp?

We updated recently (I'd not realised it was after the release) to ensure that inherited properties don't get redefined with a different ID, so yes, untp-core for this property which is defined in untp-core.

> I also see BovineAnimal in DLP context?

Sorry, it turns out I was CTRL-F'ing for `BovineAnimal` in the [instance document](https://jargon.sh/user/aatp/DigitalLivestockPassport/v/working/artefacts/jsonSchemas/DigitalLivestockPassport_instance.json?class=DigitalLivestockPassport_instance) rather than the context. I should have double-checked that.

**Comment by colugo** [comment]
Why not dpp, as that's the domain that declared the property?
If I make jargon produce 'untp-core:conformityClaim', then the biggest fallout that I can automatically detect is in DCC (I have a regression suite of UNTP domains, and their expected schemas, samples and contexts - but only for DPP, DCC and TE at the moment).

This is a diff from that test, where a few things that were untp-core are now untp-dcc. Looking at the domain, this seems to be correct, as there are local Facilty + Product classes there. Also there are local 'ConformityAssesement.assessment' and 'ConformityAttestation.scope' properties.

```

    - Expected
    + Received

    @@ -166,11 +166,11 @@
                  "registeredId": Object {
                    "@id": "untp-core:registeredId",
                    "@type": "xsd:string",
                  },
                },
    -           "@id": "untp-core:Facility",
    +           "@id": "untp-dcc:Facility",
                "@type": "@id",
              },
              "assessedOrganisation": Object {
                "@context": Object {
                  "@protected": true,
    @@ -208,11 +208,11 @@
                  "serialNumber": Object {
                    "@id": "untp-core:serialNumber",
                    "@type": "xsd:string",
                  },
                },
    -           "@id": "untp-core:Product",
    +           "@id": "untp-dcc:Product",
                "@type": "@id",
              },
              "assessmentCriteria": Object {
                "@id": "untp-core:assessmentCriteria",
                "@type": "@id",
    @@ -349,11 +349,11 @@
          },
          "ConformityAttestation": Object {
            "@context": Object {
              "@protected": true,
              "assessment": Object {
    -           "@id": "untp-core:assessment",
    +           "@id": "untp-dcc:assessment",
                "@type": "@id",
              },
              "assessmentLevel": Object {
                "@context": Object {
                  "@protected": true,
    @@ -474,11 +474,11 @@
                },
                "@id": "untp-core:Party",
                "@type": "@id",
              },
              "scope": Object {
    -           "@id": "untp-core:scope",
    +           "@id": "untp-dcc:scope",
                "@type": "@id",
              },
            },
            "@id": "untp-dcc:ConformityAttestation",
            "@protected": true,
```

**Comment by absoludity** [comment]
> Why not dpp, as that's the domain that declared the property?

Yes, you're right. I'd missed that it isn't defined on the core model, so given it is defined in DPP itself, then that specific field should be dpp.

> 
> This is a diff from that test, where a few things that were untp-core are now untp-dcc. Looking at the domain, this seems to be correct, as there are local Facilty + Product classes there. Also there are local 'ConformityAssesement.assessment' and 'ConformityAttestation.scope' properties.

I'll check through this later this afternoon when back.

**Comment by absoludity** [comment]
> This is a diff from that test, where a few things that were untp-core are now untp-dcc. Looking at the domain, this seems to be correct, as there are local Facilty + Product classes there.

Yes, that looks correct (I think longer-term the untp models shouldn't be redefining classes full-stop, since it means that if someone needs to pull in both the core context and the dpp context, for example, that `Product` will be redefined differently, but I'll create an issue in spec-untp for that later).

> Also there are local 'ConformityAssesement.assessment' and 'ConformityAttestation.scope' properties.

Yes, agreed that these should also change as per your diff.

**Comment by jargon-sh** [comment]
I've deployed the changes

**Comment by absoludity** [comment]
Looking at DCC (which I've reloaded and resaved twice), I can see that scope and assessment have updated as per your diff
but I'm not seeing the expected change for `Facility` or `Product` - they're still showing with the `id` of  `untp-core:Facility` and `untp-core:Product` respectively:

![Image](https://github.com/user-attachments/assets/53c42cfe-69a9-4a9e-8a12-824b6fe7d978)

**Comment by jargon-sh** [comment]
There's one untp-dcc:Facility in there, but I'm not sure this is going to
work with a DCC class called Facility that subtypes core.Facility.

The context file can only have one entry for "Facility" as it's not
namespace aware. I'm not necessarily suggesting this is causing the
problem, but the context file can only have one declaration. It's possible
that core.facility is overwriting the dcc one.

I'll investigate the cause further,  but you might want to change the names
to something other than the superclass names - and probably make that a
rule in UNTPs extension methodology.

**Comment by colugo** [comment]
If I just change `Facility` to `Facility2`, then :

<img width="242" alt="Image" src="https://github.com/user-attachments/assets/dd02c839-5b49-424e-82ae-16823b37eb8f" />

appears in the context file.

It also includes `Facility`:

<img width="227" alt="Image" src="https://github.com/user-attachments/assets/053fea99-38d3-4a0f-b46e-d8adc8e95a2f" />

So it seems like the name collision is preventing you from seeing `"@id": "untp-dcc:Facility"`.

I think there are 2 options.

1. Change `Facility` and `Product` to something else in DCC, and instigate a rule that prevents extensions (or even domains within the UNTP umbrella) from declaring classes with names that have already been defined. Jargon can help with a rule to enforce this (but only detecting instances of the problem via a domain's imports, so if DPP and DCC both declare 'Claim', Jargon won't detect it unless `Claim` is already declared in Core - or some other domain they both import).

2. Introduce namespaces into the type names in the context file - something like

```
    "untp-dcc_Facility": {
      "@protected": true,
      "@id": "untp-dcc:untp-dcc_Facility",
      "@context": {}
...

    "untp-core_Facility": {
      "@protected": true,
      "@id": "untp-core:untp-core_Facility",
      "@context": {}

```
which is pretty ugly - the namespaced names would also need to appear in all of the `type` properties that jargon generates.


I think 1) makes more sense.

**Comment by absoludity** [comment]
> The context file can only have one entry for "Facility" as it's not namespace aware.

Yep, and jargon seems to know that the one it needs to have is the one defined in DCC (since the one in the context has the extra property added in DCC). If a domain uses core Product as a base-class to define a new Product and refers to it from properties, then the context will always need that new product. Of course, if a domain did that but also had other properties referring to the core `Product` as well as the original references to the DCC `Product`, then it would not be solveable, and so...

> but you might want to change the names to something other than the superclass names - and probably make that a rule in UNTPs extension methodology.

Yeah, that's what [I meant above](https://github.com/jargon-sh/issues/issues/42#issuecomment-2712791306) with

> (I think longer-term the untp models shouldn't be redefining classes full-stop, since it means that if someone needs to pull in both the core context and the dpp context, for example, that Product will be redefined differently, but I'll create an issue in spec-untp for that later)

From what I understand from the history, the `untp-core` was meant to be like a library of re-usable parts that could be extended as they are here, **or** used as they are - which leads to this possible conflict. I'll be creating a ticket in spec-untp about that first thing tomorrow, as I do think the assumption needs to change longer term. But yes, thanks, if your investigation does show why it's currently combining the two even though we shouldn't have a conflict here, that would be great shorter term.

**Comment by absoludity** [comment]
> If I just change `Facility` to `Facility2`, then :
...
> appears in the context file.
> 
> It also includes `Facility`:

Yes, but why? There's no reason I can see of that untp-core's `Facility` should be in the context file: it's not referenced by any property in the domain AFAIK. It's only relevance to the domain is that it's used to create the DCC `Facility`. I'm not saying you should change it's inclusion, just that I don't understand why it is included in the context at all (the context defines terms that are used by properties). 

> 
> So it seems like the name collision is preventing you from seeing `"@id": "untp-dcc:Facility"`.

Yep.

> 
> I think there are 2 options.
> 
>     1. Change `Facility` and `Product` to something else in DCC, and instigate a rule that prevents extensions (or even domains within the UNTP umbrella) from declaring classes with names that have already been defined. Jargon can help with a rule to enforce this (but only detecting instances of the problem via a domain's imports, so if DPP and DCC both declare 'Claim', Jargon won't detect it unless `Claim` is already declared in Core - or some other domain they both import).
> 
>     2. Introduce namespaces into the type names in the context file - something like

Totally agree - 2 is a no-go.

...
> 
> I think 1) makes more sense.

A slight different: I'll audit the use of all the core classes tomorrow as part of the issue I'll create, but I think it might make more sense to rename the core `Facility` and `Product` to `FacilityBase` and `ProductBase` in the "reusable library" for now (if that's all they're used for, but I'll confirm), so that the terms in the actual DPP and DCC don't need to change. But the key point is the same: terms should not be redefined in different domains.

**Comment by colugo** [comment]
> Yes, but why? There's no reason I can see of that untp-core's Facility should be in the context file

Context files are generated for the entire domain (as opposed to schemas, which have a root), and thus represent the entire information model of the domain.
The rough algorithm is: 
- Add all the Blue classes from this domain, and all the imported json-ld-generating domains as top-level entries
- Fill in the Green classes inline where referenced.

I'll have to think about the consequences further, but Jargon also supports aggregation, which could be used as a kludge around subclassing.

<img width="800" alt="Image" src="https://github.com/user-attachments/assets/9ed33b16-97ab-4f5e-82f3-3ffaa30d70e2" />

`LocalProduct1` has a property that is a type of `untp-core:Product` and so has this in it's @context
```
        "untpProduct": {
          "@id": "untp-core:untpProduct",
          "@type": "@id"
        }
```

`LocalProduct2` has an aggregated property of `untp-core:Product` which inlines all of Product's properties as if they were locally defined in `LocalProduct2`. It's a little less clear what's happening compared to subclassing, but achieves a similar outcome.

There's been almost 0 usage of aggregation and json-ld, so I suspect there will be gremlins, but it could be a better approach than `xxxBase` style of classes in untp-core, and instead allows a more mixin/trait/behaviour style of composing classes.

--Edit--
I shoud also add that you will lose the `Product` entry in `LocalProduct2`'s `type` property, as it's no longer a `Product` - this may also be a reason not to do it.

**Comment by colugo** [comment]
Jargon has some degree of impact assessment/usage reporting.

1) Navigate to the domain you're interested in seeing the usage of (in this case untp-core)
2) Click the reporting button, then 'class, property and code usage'

<img width="413" alt="Image" src="https://github.com/user-attachments/assets/30ec41de-1175-408f-b104-031d2069a3e8" />

3) Select the domains that you want to search in (these domains have a release that imports the domain you're in)

<img width="1469" alt="Image" src="https://github.com/user-attachments/assets/d25f15f6-4074-45c1-a3c9-2366cc51c821" />

4) Select the classes/codes you want to search for
5) Hit run

**Comment by absoludity** [comment]
Great, thanks. I'm using that now to write up the issue.


> The rough algorithm is:
> 
>     * Add all the Blue classes from this domain, and all the imported json-ld-generating domains as top-level entries

The above line is what is different from my expectations (not saying my expectations were correct). FWIW, my expectation is that it would be more specifically:

 - Add all the Blue classes from this domain, and all the blue classes from the imported json-ld-generating domains **if the class is referenced in this domain**,  as top-level entries

That's why I was surprised to see the untp-core `Facility` in the context (or interfering with the context), given it wasn't referenced at all and was only used in the domain to define the DCC Facility.

**Comment by colugo** [comment]
That was the approach initially, and jargon forced you to specify which class the context file was for. When that was taken away, it became for the whole domain.

It can be revisited though - once there are enough passing tests to ensure validity of the artefact suite.

**Comment by absoludity** [comment]
I think we both agree that either way, in the long-term, it's better if UNTP classes don't get redefined in other domains, so I'll continue writing up the issue (as it'll be worthwhile either way).

Regarding the "and all the blue classes from the imported json-ld-generating domains"... if untp-core wasn't json-ld-generating (ie. switched off in the settings), would an importing domain only expose blue classes from core which are referenced in the domain then? Or would it not expose them at all? (Just interested to know if that could be a short-cut for now).

**Comment by colugo** [comment]
Yes, that might work. There may be other consequences, but the context diff looks like [this](https://www.diffchecker.com/1LxaThju/)

**Comment by colugo** [comment]
It won't work for DLP though, any unused DPP classes will appear as DPP is generating

**Comment by absoludity** [comment]
Thanks for checking. Yeah, I think that diff re-enforces that we shouldn't be re-defining entities at all, as I can see other cases there, such as the `WebRenderingTemplate2022` and `RenderTemplate2024` which are meant to be `untp-core` classes that are just included in that context (as in, we don't want each domain to define them with a different ID, which is what's happening there when core isn't an ld-generating domain).

Aside: the only way I could actually ensure that `WebRenderingTemplate2022` and `RenderTemplate2024` were included from core in each context was to inherit-but-not-modify them in each domain like:

![Image](https://github.com/user-attachments/assets/2774a9ec-eebc-49b0-af3a-f1755c3d46d1)

Let me know if there's a better way.

**Comment by absoludity** [comment]
I think this can be closed now, given that we agreed that the entities shouldn't be being redefined in the model at all (as per https://github.com/uncefact/spec-untp/issues/323)?
